export const EXAMPLE_FEATCH_LIST_BEGIN = "EXAMPLE_FEATCH_LIST_BEGIN";
export const EXAMPLE_FEATCH_LIST_SUCCESS = "EXAMPLE_FEATCH_LIST_SUCCESS";
export const EXAMPLE_FEATCH_LIST_FAIL = "EXAMPLE_FEATCH_LIST_FAIL";
